# Generated by Django 3.1.3 on 2020-11-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', models.CharField(default='', max_length=100, unique=True)),
                ('derivative', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
    ]
